server:
  port: 8981
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NipunLiyanage/ms-config-store
          default-label: master
          search-paths:
            - 'service-config/*service'
